###############################################################################
# $Id: Makefile,v 1.1 2003/07/12 18:29:57 layekers Exp $
###############################################################################

SUB_DIRS= java cpp
ALL_SUB_DIRS= $(SUB_DIRS)

ifndef TOPDIR
        TOPDIR  = $(shell pwd)/../..
endif

include $(TOPDIR)/scripts/Config.make
include $(TOPDIR)/scripts/Rules.make
